class LocalizationMap {
  static Map<String, String> get codesEN => {
    "please_enter_your_email": "Please enter your email",
    "enter_a_valid_email": "Enter a valid email",
    "emojis_are_not_allowed": "Emojis are not allowed",
    "please_enter_your_password": "Please enter your password",
    "password_consists_minimum_6_character":
        "Password consists minimum 6 character",
    "please_enter_your_name": "Please enter your name",
    "leading_trailing_space_not_allowed": "Leading trailing space not allowed",
    "invalid_name": "Invalid name",
    "password_must_be_at_least": "Password must be at least 6 characters long.",
    "password_must_contains_at_least_one_number":
        "Password must contain at least one number.",
    "password_must_contains_at_least_one_special_character":
        "Password must contain at least one special character.",
    "password_must_contains_at_least_one_upper_case":
        "Password must contain at least one upper case letter.",
    "password_must_contains_at_least_one_lower_case":
        "Password must contain at least one lower case letter.",
    "please_re_enter_your_password": "Please re-enter your password",
    "password_did_not_match": "Password did not match",
    "please_select_your_date_of_birth": "Please select your date of birth",
    "please_enter_your_otp": "Please enter your OTP",
    "invalid_otp": "Invalid OTP",
    "field_required": "Field required",
    "press_again_to_exit": "Press again to exit",
    "modes": "Modes",
    "skip": "Skip",
    "sign_up ": "Sign Up ",
    "adjust_brightness_colors_and_schedules_to_match_your_aquarium_needs":
        "Adjust brightness, colors, and schedules to match your aquarium's needs.",
    "personalized_aquarium_lighting": "Personalized\nAquarium Lighting",
    "Coordinate_multiple_lights_for_a_harmonious_aquarium_environment":
        "Coordinate multiple lights for a harmonious aquarium environment.",
    "sync_multiple_lights": "Sync Multiple Lights",
    "control_your_aquarium_lighting_like_never_before":
        "Control your aquarium lighting like never before.",
    "light_up_your_aquarium": "Light Up Your Aquarium",
    "login_to_your_account": "Login to your account",
    "get_started": "Get Started",
    "adjust_channels_schedules_control_brightness_and_enable_acclimation_for_perfect_lighting":
        "Adjust channels, schedules, control brightness, and enable acclimation for perfect lighting.",
    "set_channels": "Set Channels",
    "customize_six_light_channels_to_match_your_aquarium_needs":
        "Customize 6 light channels to match your aquarium needs.",
    "scheduling": "Scheduling",
    "create_a_lighting_schedule_to_automate_your_aquariums_day_and_night_cycle":
        "Create a lighting schedule to automate your aquarium's day and night cycle.",
    "brightness_control": "Brightness Control",
    "adjust_the_brightness_level_across_all_light_channels_for_optimal_illumination":
        "Adjust the brightness level across all light channels for optimal illumination.",
    "customize_each_channel_by_selecting_colors_to_create_a_perfect_balance_for_your_aquarium":
        "Customize each channel by selecting colors to create a perfect balance for your aquarium.",
    "channels": "Channels",
    "save": "Save",
    "enter_otp": "Enter OTP",
    "login": "Login",
    "forgot_password?": "Forgot password?",
    "forgot_password": "Forgot Password",
    "sign_up": "Sign Up",
    "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
    "password": "Password",
    "enter_email": "Enter Email",
    "are_you_sure_you_want_to_delete_this_account":
        "Are you sure you want to delete this account",
    "enter_password": "Enter Password",
    "enter_your_password": "Enter your password",
    "email_address": "Email Address",
    "please_enter_your_details_below_to_continue":
        "Please enter your details below to continue",
    "modes": "Modes",
    "adjust_channels_schedules_control_brightness_and_enable_acclimation_for_perfect_lighting":
        "Adjust channels, schedules, control brightness, and enable acclimation for perfect lighting.",
    "set_channels": "Set Channels",
    "customize_six_light_channels_to_match_your_aquarium_needs":
        "Customize 6 light channels to match your aquarium needs.",
    "scheduling": "Scheduling",
    "create_a_lighting_schedule_to_automate_your_aquariums_day_and_night_cycle":
        "Create a lighting schedule to automate your aquarium's day and night cycle.",
    "brightness_control": "Brightness Control",
    "adjust_the_brightness_level_across_all_light_channels_for_optimal_illumination":
        "Adjust the brightness level across all light channels for optimal illumination.",
    "customize_each_channel_by_selecting_colors_to_create_a_perfect_balance_for_your_aquarium":
        "Customize each channel by selecting colors to create a perfect balance for your aquarium.",
    "channels": "Channels",
    "save": "Save",
    "channels_have_been_set_successfully":
        "Channels have been set successfully.",
    "channel_set": "Channel Set",
    "save": "Save",
    "add_device": "Add Device",
    "add_a_Bluetooth_device_to_proceed": "Add a Bluetooth device to proceed",
    "add": "Add",
    "name": "Name",
    "confirm_password": "Confirm Password",
    "enter_confirm_password": "Enter confirm password",
    "enter_name": "Enter name",
    "connected_device": "Connected Device",
    "create_an_account_to_get_started": "Create an account to get started",
    "connected": "Connected",
    "click_to_upload_an_image": "Click to upload an image",
    "error": "Error",
    "already_have_an_account": "Already have an account?",
    "_optional_": "(optional)",
    "disconnected_device": "Disconnected Device",
    "disconnected": "Disconnected",
    "proceed": "Proceed",
    "resend": "Resend",
    "you_can_now_login_your_account": "You can now login your account.",
    "congratulate_subtitle":
        "Your password has been updated successfully. You can now log in securely using your new password.",
    "verify": "Verify",
    "enter_your_registered_email_to_request_a_password_reset":
        "Enter your registered email to request a\npassword reset.",
    "verify_your_account": "Verify Your Account",
    "did_not_received_code": "Did not received code",
    "device_not_available": "Device not available",
    "unable_to_connect": "Unable to connect, device is out of range",
    "reset_pass_subtitle": "A 6 Digit PIN has been sent to your email",
    "verification_subTitle":
        "We’ve sent a 6-digit code to your email.\nEnter the code below to verify your account.",
    "verification_sucessfully_completed": "Verification Successfully\nCompleted",
    "find_device": "Find Device",
    "new_time_added": "New Time Added",
    "the_time_has_been_added_successfully":
        "The time has been added successfully.",
    "the_time_has_been_added_successfully": "The time has been added successfully.",
    "available_devices": "Available devices",
    "pair": "Pair",
    "pairing": "Pairing",
    "are_you_sure_you_want_to_remove_this_device": "Are you sure you want to remove this device?",
    "acclimaation": "Acclimilation",
    "save":"Save",
    "": "",
    "reset_password": "Reset Password",
    "change_password": "Change Password",
    "congratulations": "Congratulations",
    "resend_code": "Resend Code",
    "terms_conditions": "Terms & Conditions",
    "profile": "Profile",
    "privacy_policy": "Privacy Policy",
    "update": "Update",
    "logout": "Logout",
    "support": "Support",
    "yes": "Yes",
    "no": "No",
    "i_agree_with": "I agree with",
    "write_here": "Write here",
    "re_enter_your_new_password": "Re-enter your New Password",
    "enter_your_new_password": "Enter your New Password",
    "enter_your_current_password": "Enter your Current Password",
    "terms_and_conditions": "Terms and Conditions",

    "enter_phone_number": "Enter phone number",
    "submit": "Submit",
    "_in_detail_please_describe_the_issues_you_are_facing":
        "4. In detail, please describe the issues you are facing?",
    "_channel_options": "3. Channel Options:",
    "software_issue": "Software issue",
    "hardware_issue": "Hardware issue",
    "indicator_light_showing_problem": "Indicator light showing problem",
    "_select_problem": "2. Select Problem:",
    "which_led_lighting_system_is_experiencing_issues":
        "1. Which LED lighting system is experiencing issues?",
    "please_select": "Please select",
    "search_by_country_name_or_code": "Search by country name or code",
    "delete_account": "Delete Account",
    "once_deleted_your_account_and_data_cannot_be_recovered":
        "Once deleted, your account and data cannot be recovered.",
    "update_your_password_to_keep_your_account_secure":
        "Update your password to keep your account secure.",
    "edit": "Edit",
    "password_has_been_changed_successfully":
        "Password has been changed successfully.",
    "password_changed": "Password Changed",
    "ticket_has_been_created_successfully":
        "Ticket has been created successfully.",
    "ticket_created": "Ticket Created",
    "account_has_been_deleted_successfully":
        "Account has been deleted successfully.",
    "account_deleted": "Account Deleted",
    "profile_has_been_updated_successfully":
        "Profile has been updated successfully.",
    "profile_updated": "Profile Updated",
    "gallery": "Gallery",
    "camera": "Camera",
    "enter_your_phone": "Enter your phone",
    "please_enter_your_phone_number": "Please enter your phone number",
    "edit_profile": "Edit Profile",
    "profile_successfully_updated": "Profile successfully updated",
    "profile_picture": "Profile picture",
    "change_pass_subtitle":
        "Set a new password with an uppercase letter, a lowercase letter, a number, and a special character.",
    "no_device_found":"No Device Found",
    "please_turn_on_Bluetooth_to_connect":"Please turn on Bluetooth to connect",
    "search_device":"Search Device",
    "no_device_in_range":"No device in range",
    "retry":"Retry",
    "bluetooth_pairing_request":"Bluetooth Pairing Request",
    "wants_to_pair_with_your_phone":"wants to pair with your phone",
    "cancel":"Cancel",
    "device_settings":"Device Settings",
    "connect_wifi":"Connect Wifi",
    "import_properties":"Import Properties",
    "export_properties":"Export Properties",
    "time_zone":"Time Zone",
    "device_error":"Device Error",
    "wifi_connected":"Wifi Connected",
    "temp_probe":"Temp Probe",
    "ntp":"NTP",
    "led_temp":"LED Temp",
    "servers_connection":"Servers Connection",
    "wifi_turned_off":"Wifi Turned Off",
    "please_turn_on_wifi_to_connect":"Please turn on Wifi to connect",
    "connect":"Connect",
    "password_consists_minimum_8_character":
    "Password consists minimum 8 character",
    "android_wifi":"Android Wifi",
    "disconnect":"Disconnect",
    "":"",
    "cancel":'Cancel',
    "all_your_graph_data_will_be_removed_are_you_sure_you_want_to_rest":"All your graph data will be removed. Are you sure you want to reset?",
    "the_graph_has_been_reset_successfully":"The graph has been reset successfully.",
    "graph_reset":"Graph Reset",
    "acclimation_has_been_set_successfully":"Acclimation has been set successfully",
    "acclimation_added":"Acclimation Added",
    "acclimation_view":"Acclimation View",
    "acclimation":"Acclimation",
    "start_intensity":"Start Intensity",
    "to_enable_acclimation_you_need_to_set_up_a_lighting_schedule_first":"To enable acclimation, you need to set up a lighting schedule first.",
     "schedule_now":"Schedule Now",
     "schedule_later":"Schedule Later",
    "kindly_select_number_of_days_for_acclimation":"Kindly select number of days for acclimation.",
    "brightness":"Brightness",
    "moon_light":"Moon Light",
   "set_moonlight_to_create_a_natural_moonlight_effect_for_your_aquarium":"Set moonlight to create a natural moonlight effect for your aquarium.",
    "import":"Import",
    "connected_devices":"Connected Devices",
    "properties_imported":"Properties Imported",
    "properties_has_been_imported_successfully":"Properties has been imported successfully",
    "available_networks":"Available Networks",
    "adjust_the_brightness_level_across_all_light_channels_for_optimal_illumination":"Adjust the brightness level across all light channels for optimal illumination.",
   "set_moonlight_to_create_a_natural_moonlight_effect_for_your_aquarium":"Set moonlight to create a natural moonlight effect for your aquarium.",
    "moon_light_has_been_updated_successfully":"Moon light has been updated successfully.",
    "moon_light_updated":"Moon light Updated",
    "brightness_level_has_been_updated_successfully":"Brightness level has been updated successfully.",
    "brightness_level_updated":"Brightness Level Updated",
    "schedule_intensity":"Schedule Intensity",
    "set_overall_intensity_of_the_schedule":"Set overall intensity of the schedule.",
    "log_in":"Log In",
    "log_in_":"Log in",
    "please_accept_terms":"Please accept the Terms & Conditions.",
    "paired_successfully":"Paired Successfully"
  };

  static String getTranslatedValues(String key) {
    return codesEN[key] ?? "Text not found";
  }
}

extension Localize on String {
  String L() {
    return LocalizationMap.getTranslatedValues(this);
  }
}
